name: mariner
version: git
license: GPL-3.0-only
summary: Command line torrent searcher.
description: |
  Mariner is a command line torrent searcher. It offers simple interface and a streamlined experience.

grade: stable
confinement: strict

parts:
  snapd-xdg-open:
    source: https://github.com/ubuntu-core/snapd-xdg-open.git
    plugin: copy
    files:
      data/xdg-open: bin/xdg-open
    stage-packages:
      - dbus
  mariner:
    source: https://gitlab.com/radek-sprta/mariner.git
    plugin: python
    python-version: python3
    stage-packages:
      - libc6
      - libxml2

apps:
  mariner:
    command: bin/mariner
    plugs:
      - network
      - home
